services:
  postgres:
    image: postgres:17
    restart: on-failure
    container_name: ${DOCKER_CONTAINER}
    environment:
      - POSTGRES_DB=${POSTGRES_SCHEMA}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${HOST_PORT}:5432"
    volumes:
      - ./:/SQL/PostgreSQL/The Applied SQL Data Analytics Workshop/
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
